=== C4J/Commander4j/b5web_t10/WebContent/xml/view/view.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT SQL (jdbcDriver+)>
<!ELEMENT jdbcDriver (statement+)>
<!ELEMENT statement (id, text)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT text (#PCDATA)>
<!ATTLIST jdbcDriver Type  CDATA #REQUIRED>

=== C4J/Commander4j/b6web_t10/WebContent/xml/view/view.oracle.jdbc.driver.OracleDriver.xml
<?xml version="1.0" encoding="UTF-8"?> <!DOCTYPE SQL SYSTEM "view.dtd"> 
<SQL>
	<jdbcDriver Type="oracle.jdbc.driver.OracleDriver">
		<?VIEWS ?>
		<statement>
			<id>view_group_permissions</id>
			<text>(select p.group_id,m.* from {schema}SYS_GROUP_PERMISSIONS p, {schema}SYS_MODULES m where m.module_id = p.module_id)</text>
		</statement>
		<statement>
			<id>view_menu_structure</id>
			<text>(select SYS_MENUS.*, SYS_MODULES.resource_key, SYS_MODULES.rf_active, SYS_MODULES.dk_active, SYS_MODULES.module_type, SYS_MODULES.hint, SYS_MODULES.icon_filename from {schema}SYS_MENUS, {schema}SYS_MODULES where SYS_MODULES.module_id = SYS_MENUS.module_id)</text>
		</statement>
		<statement>
			<id>view_toolbar</id>
			<text>(select SYS_TOOLBAR.*, SYS_MODULES.resource_key, SYS_MODULES.rf_active, SYS_MODULES.dk_active, SYS_MODULES.module_type, SYS_MODULES.hint, SYS_MODULES.icon_filename from {schema}SYS_TOOLBAR, {schema}SYS_MODULES where SYS_MODULES.module_id = SYS_TOOLBAR.module_id)</text>
		</statement>
		<statement>
			<id>view_rf_menu</id>
			<text>(select SYS_RF_MENU.*, SYS_MODULES.resource_key, SYS_MODULES.rf_active, SYS_MODULES.dk_active, SYS_MODULES.module_type, SYS_MODULES.hint, SYS_MODULES.icon_filename from {schema}SYS_RF_MENU, {schema}SYS_MODULES where SYS_MODULES.module_id = SYS_RF_MENU.module_id)</text>
		</statement>
		<statement>
			<id>view_security</id>
			<text>(select sugm.user_id,sgp.module_id from {schema}SYS_USER_GROUP_MEMBERSHIP sugm, {schema}SYS_GROUP_PERMISSIONS sgp where sgp.group_id = sugm.group_id)</text>
		</statement>
		<statement>
			<id>view_pallet_expiry</id>
			<text>VIEW_PALLET_EXPIRY</text>
		</statement>
		<statement>
			<id>view_pallet_history_expiry</id>
			<text>VIEW_PALLET_HISTORY_EXPIRY</text>
		</statement>
		<statement>
			<id>view_pallet_history</id>
			<text>VIEW_PALLET_HISTORY</text>
		</statement>
	</jdbcDriver>
</SQL>
